# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/code-frame-7.12.11" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.12.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.12.11.tgz";
        sha512 = "Zt1yodBx1UcyiePMSkWnU4hPqhwq7hGi2nFL1LeA3EUl+q2LQx16MISgJ0+z7dnmgvP9QtIleuETGOiOH1RcIw==";
      };
    };
    "@babel/helper-validator-identifier-7.15.7" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.15.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.15.7.tgz";
        sha512 = "K4JvCtQqad9OY2+yTU8w+E82ywk/fe+ELNlt1G8z3bVGlZfn/hOcQQsUhGhW/N+tb3fxK800wLtKOE/aM0m72w==";
      };
    };
    "@babel/highlight-7.16.0" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.16.0.tgz";
        sha512 = "t8MH41kUQylBtu2+4IQA3atqevA2lRgqA2wyVB/YiWmsDSuylZZuXOUy9ric30hfzauEFfdsuk/eXTRrGrfd0g==";
      };
    };
    "@eslint/eslintrc-0.4.3" = {
      name = "_at_eslint_slash_eslintrc";
      packageName = "@eslint/eslintrc";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/eslintrc/-/eslintrc-0.4.3.tgz";
        sha512 = "J6KFFz5QCYUJq3pf0mjEcCJVERbzv71PUIDczuh9JkwGEzced6CO5ADLHB1rbf/+oPBtoPfMYNOpGDzCANlbXw==";
      };
    };
    "@fontsource/fira-mono-4.5.0" = {
      name = "_at_fontsource_slash_fira-mono";
      packageName = "@fontsource/fira-mono";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fontsource/fira-mono/-/fira-mono-4.5.0.tgz";
        sha512 = "KE+d3wmgq/YKM0BqgUF7p2yeBNi805Nfof1lC1wJ7E9i2EWoC363sGdKG+MQBVm+ei3GYZu+Bo8Xha1w1pkB7g==";
      };
    };
    "@humanwhocodes/config-array-0.5.0" = {
      name = "_at_humanwhocodes_slash_config-array";
      packageName = "@humanwhocodes/config-array";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/config-array/-/config-array-0.5.0.tgz";
        sha512 = "FagtKFz74XrTl7y6HCzQpwDfXP0yhxe9lHLD1UZxjvZIcbyRz8zTFF/yYNfSfzU414eDwZ1SrO0Qvtyf+wFMQg==";
      };
    };
    "@humanwhocodes/object-schema-1.2.1" = {
      name = "_at_humanwhocodes_slash_object-schema";
      packageName = "@humanwhocodes/object-schema";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/object-schema/-/object-schema-1.2.1.tgz";
        sha512 = "ZnQMnLV4e7hDlUvw8H+U8ASL02SS2Gn6+9Ac3wGGLIe7+je2AeAOxPY+izIPJDfFDb7eDjev0Us8MO1iFRN8hA==";
      };
    };
    "@iarna/toml-2.2.5" = {
      name = "_at_iarna_slash_toml";
      packageName = "@iarna/toml";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@iarna/toml/-/toml-2.2.5.tgz";
        sha512 = "trnsAYxU3xnS1gPHPyU961coFyLkh4gAD/0zQ5mymY4yOZ+CYvsPqUbOFSw0aDM4y0tV7tiFxL/1XfXPNC6IPg==";
      };
    };
    "@lukeed/csprng-1.0.1" = {
      name = "_at_lukeed_slash_csprng";
      packageName = "@lukeed/csprng";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@lukeed/csprng/-/csprng-1.0.1.tgz";
        sha512 = "uSvJdwQU5nK+Vdf6zxcWAY2A8r7uqe+gePwLWzJ+fsQehq18pc0I2hJKwypZ2aLM90+Er9u1xn4iLJPZ+xlL4g==";
      };
    };
    "@lukeed/uuid-2.0.0" = {
      name = "_at_lukeed_slash_uuid";
      packageName = "@lukeed/uuid";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@lukeed/uuid/-/uuid-2.0.0.tgz";
        sha512 = "dUz8OmYvlY5A9wXaroHIMSPASpSYRLCqbPvxGSyHguhtTQIy24lC+EGxQlwv71AhRCO55WOtgwhzQLpw27JaJQ==";
      };
    };
    "@rollup/pluginutils-4.1.1" = {
      name = "_at_rollup_slash_pluginutils";
      packageName = "@rollup/pluginutils";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/pluginutils/-/pluginutils-4.1.1.tgz";
        sha512 = "clDjivHqWGXi7u+0d2r2sBi4Ie6VLEAzWMIkvJLnDmxoOhBYOTfzGbOQBA32THHm11/LiJbd01tJUpJsbshSWQ==";
      };
    };
    "@sveltejs/adapter-auto-1.0.0-next.3" = {
      name = "_at_sveltejs_slash_adapter-auto";
      packageName = "@sveltejs/adapter-auto";
      version = "1.0.0-next.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/adapter-auto/-/adapter-auto-1.0.0-next.3.tgz";
        sha512 = "FVNLtr0bj/slQqA0TuoylnVsGrvBYdYL+hpp2Qy5Kg3q1m8i9bJ0aifKnaGn7m01II2KUSnpnhuRbX/HwKVDcA==";
      };
    };
    "@sveltejs/adapter-cloudflare-1.0.0-next.2" = {
      name = "_at_sveltejs_slash_adapter-cloudflare";
      packageName = "@sveltejs/adapter-cloudflare";
      version = "1.0.0-next.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/adapter-cloudflare/-/adapter-cloudflare-1.0.0-next.2.tgz";
        sha512 = "4Q7ZuoMck7wwzIO7gd8gqnm7gWflztTDHU/C1DzLr8V2UprQFQwsUE/padtQhFPXkgAiXJ8AwLksey4A8qjOsA==";
      };
    };
    "@sveltejs/adapter-netlify-1.0.0-next.35" = {
      name = "_at_sveltejs_slash_adapter-netlify";
      packageName = "@sveltejs/adapter-netlify";
      version = "1.0.0-next.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/adapter-netlify/-/adapter-netlify-1.0.0-next.35.tgz";
        sha512 = "3PC1RaRReu652ot+LC9EOjkebnZehdwvUm0zhPC8OFPJJccQwq6Y1kbHDeACIIFRTaKLIRBpuYh3idP6ffUGdw==";
      };
    };
    "@sveltejs/adapter-static-1.0.0-next.21" = {
      name = "_at_sveltejs_slash_adapter-static";
      packageName = "@sveltejs/adapter-static";
      version = "1.0.0-next.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/adapter-static/-/adapter-static-1.0.0-next.21.tgz";
        sha512 = "B4+QoUVAaANKx+mHntG8SqF45zbj3Ct4Akg/cGauo6COyfKZRhO5OsMa+wPuT2TKJBZC4eEDK0p+p9nyQBkxKQ==";
      };
    };
    "@sveltejs/adapter-vercel-1.0.0-next.31" = {
      name = "_at_sveltejs_slash_adapter-vercel";
      packageName = "@sveltejs/adapter-vercel";
      version = "1.0.0-next.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/adapter-vercel/-/adapter-vercel-1.0.0-next.31.tgz";
        sha512 = "W8p/U00B6ihVrDpwMkgEexfVUzaLmn4MRtXj//Gw4NDFfsrZR4P5wBidrOAIkCYBMvqCOHD+vbAvIiAMOaN23g==";
      };
    };
    "@sveltejs/kit-1.0.0-next.201" = {
      name = "_at_sveltejs_slash_kit";
      packageName = "@sveltejs/kit";
      version = "1.0.0-next.201";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/kit/-/kit-1.0.0-next.201.tgz";
        sha512 = "WcYexOEPWgDWOk0oOteTU5QwWykdIcOFJig+akeHqwE/jVtPURLZFtTNx0ymUWXN4S+dUXf60KF6HEMv74FHpA==";
      };
    };
    "@sveltejs/vite-plugin-svelte-1.0.0-next.30" = {
      name = "_at_sveltejs_slash_vite-plugin-svelte";
      packageName = "@sveltejs/vite-plugin-svelte";
      version = "1.0.0-next.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/vite-plugin-svelte/-/vite-plugin-svelte-1.0.0-next.30.tgz";
        sha512 = "YQqdMxjL1VgSFk4/+IY3yLwuRRapPafPiZTiaGEq1psbJYSNYUWx9F1zMm32GMsnogg3zn99mGJOqe3ld3HZSg==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "acorn-jsx-5.3.2" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-5.3.2.tgz";
        sha512 = "rq9s+JNhf0IChjtDXxllJ7g41oZk5SlXtp0LHwyA5cejwn7vKmKp4pPri6YEePv2PU65sAsegbXtIinmDFDXgQ==";
      };
    };
    "ajv-6.12.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.12.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz";
        sha512 = "j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
      };
    };
    "ajv-8.8.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "8.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-8.8.2.tgz";
        sha512 = "x9VuX+R/jcFj1DHo/fCp99esgGDWiHENrKxaCENuCxpoMCmAt/COCGVDwA7kleEpEzJjDnvh3yGoOuLu0Dtllw==";
      };
    };
    "ansi-colors-4.1.1" = {
      name = "ansi-colors";
      packageName = "ansi-colors";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.1.tgz";
        sha512 = "JoX0apGbHaUJBNl6yF+p6JAFYZ666/hhCGKN5t9QFjbJQKUU/g8MNbFDbvfrgKXvI1QpZplPOnwIo99lX/AAmA==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "astral-regex-2.0.0" = {
      name = "astral-regex";
      packageName = "astral-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/astral-regex/-/astral-regex-2.0.0.tgz";
        sha512 = "Z7tMw1ytTXt5jqMcOP+OQteU1VuNK9Y02uuJtKQ1Sv69jXQKKg5cibLwGJow8yzZP+eAc18EmLGPal0bp36rvQ==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "callsites-3.1.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz";
        sha512 = "P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "cheap-watch-1.0.4" = {
      name = "cheap-watch";
      packageName = "cheap-watch";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cheap-watch/-/cheap-watch-1.0.4.tgz";
        sha512 = "QR/9FrtRL5fjfUJBhAKCdi0lSRQ3rVRRum3GF9wDKp2TJbEIMGhUEr2yU8lORzm9Isdjx7/k9S0DFDx+z5VGtw==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "cookie-0.4.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.4.1.tgz";
        sha512 = "ZwrFkGJxUR3EIoXtO+yVE69Eb7KlixbaeAWfBQB9vVsNn/o+Yw69gBWSSDK825hQNdN+wF8zELf3dFNl/kxkUA==";
      };
    };
    "cross-spawn-7.0.3" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz";
        sha512 = "iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==";
      };
    };
    "debug-4.3.2" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.2.tgz";
        sha512 = "mOp8wKcvj7XxC78zLgw/ZA+6TSgkoE2C/ienthhRD298T7UNwAg9diBpLRxC0mOezLl4B0xV7M0cCO6P/O0Xhw==";
      };
    };
    "deep-is-0.1.4" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.4.tgz";
        sha512 = "oIPzksmTg4/MriiaYGO+okXDT7ztn/w3Eptv/+gSIdMdKsJo0u4CfYNFJPy+4SKMuCqGw2wxnA+URMg3t8a/bQ==";
      };
    };
    "doctrine-3.0.0" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-3.0.0.tgz";
        sha512 = "yS+Q5i3hBf7GBkd4KG8a7eBNNWNGLTaEwwYWUijIYM7zrlYDM0BFXHjjPWlWZ1Rg7UaddZeIDmi9jF3HmqiQ2w==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "enquirer-2.3.6" = {
      name = "enquirer";
      packageName = "enquirer";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/enquirer/-/enquirer-2.3.6.tgz";
        sha512 = "yjNnPr315/FjS4zIsUxYguYUPP2e1NK4d7E7ZOLiyYCcbFBiTMyID+2wvm2w6+pZ/odMA7cRkjhsPbltwBOrLg==";
      };
    };
    "esbuild-0.13.15" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.13.15.tgz";
        sha512 = "raCxt02HBKv8RJxE8vkTSCXGIyKHdEdGfUmiYb8wnabnaEmHzyW7DCHb5tEN0xU8ryqg5xw54mcwnYkC4x3AIw==";
      };
    };
    "esbuild-android-arm64-0.13.15" = {
      name = "esbuild-android-arm64";
      packageName = "esbuild-android-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-arm64/-/esbuild-android-arm64-0.13.15.tgz";
        sha512 = "m602nft/XXeO8YQPUDVoHfjyRVPdPgjyyXOxZ44MK/agewFFkPa8tUo6lAzSWh5Ui5PB4KR9UIFTSBKh/RrCmg==";
      };
    };
    "esbuild-darwin-64-0.13.15" = {
      name = "esbuild-darwin-64";
      packageName = "esbuild-darwin-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-64/-/esbuild-darwin-64-0.13.15.tgz";
        sha512 = "ihOQRGs2yyp7t5bArCwnvn2Atr6X4axqPpEdCFPVp7iUj4cVSdisgvEKdNR7yH3JDjW6aQDw40iQFoTqejqxvQ==";
      };
    };
    "esbuild-darwin-arm64-0.13.15" = {
      name = "esbuild-darwin-arm64";
      packageName = "esbuild-darwin-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-arm64/-/esbuild-darwin-arm64-0.13.15.tgz";
        sha512 = "i1FZssTVxUqNlJ6cBTj5YQj4imWy3m49RZRnHhLpefFIh0To05ow9DTrXROTE1urGTQCloFUXTX8QfGJy1P8dQ==";
      };
    };
    "esbuild-freebsd-64-0.13.15" = {
      name = "esbuild-freebsd-64";
      packageName = "esbuild-freebsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-64/-/esbuild-freebsd-64-0.13.15.tgz";
        sha512 = "G3dLBXUI6lC6Z09/x+WtXBXbOYQZ0E8TDBqvn7aMaOCzryJs8LyVXKY4CPnHFXZAbSwkCbqiPuSQ1+HhrNk7EA==";
      };
    };
    "esbuild-freebsd-arm64-0.13.15" = {
      name = "esbuild-freebsd-arm64";
      packageName = "esbuild-freebsd-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-arm64/-/esbuild-freebsd-arm64-0.13.15.tgz";
        sha512 = "KJx0fzEDf1uhNOZQStV4ujg30WlnwqUASaGSFPhznLM/bbheu9HhqZ6mJJZM32lkyfGJikw0jg7v3S0oAvtvQQ==";
      };
    };
    "esbuild-linux-32-0.13.15" = {
      name = "esbuild-linux-32";
      packageName = "esbuild-linux-32";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-32/-/esbuild-linux-32-0.13.15.tgz";
        sha512 = "ZvTBPk0YWCLMCXiFmD5EUtB30zIPvC5Itxz0mdTu/xZBbbHJftQgLWY49wEPSn2T/TxahYCRDWun5smRa0Tu+g==";
      };
    };
    "esbuild-linux-64-0.13.15" = {
      name = "esbuild-linux-64";
      packageName = "esbuild-linux-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.13.15.tgz";
        sha512 = "eCKzkNSLywNeQTRBxJRQ0jxRCl2YWdMB3+PkWFo2BBQYC5mISLIVIjThNtn6HUNqua1pnvgP5xX0nHbZbPj5oA==";
      };
    };
    "esbuild-linux-arm-0.13.15" = {
      name = "esbuild-linux-arm";
      packageName = "esbuild-linux-arm";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm/-/esbuild-linux-arm-0.13.15.tgz";
        sha512 = "wUHttDi/ol0tD8ZgUMDH8Ef7IbDX+/UsWJOXaAyTdkT7Yy9ZBqPg8bgB/Dn3CZ9SBpNieozrPRHm0BGww7W/jA==";
      };
    };
    "esbuild-linux-arm64-0.13.15" = {
      name = "esbuild-linux-arm64";
      packageName = "esbuild-linux-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm64/-/esbuild-linux-arm64-0.13.15.tgz";
        sha512 = "bYpuUlN6qYU9slzr/ltyLTR9YTBS7qUDymO8SV7kjeNext61OdmqFAzuVZom+OLW1HPHseBfJ/JfdSlx8oTUoA==";
      };
    };
    "esbuild-linux-mips64le-0.13.15" = {
      name = "esbuild-linux-mips64le";
      packageName = "esbuild-linux-mips64le";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-mips64le/-/esbuild-linux-mips64le-0.13.15.tgz";
        sha512 = "KlVjIG828uFPyJkO/8gKwy9RbXhCEUeFsCGOJBepUlpa7G8/SeZgncUEz/tOOUJTcWMTmFMtdd3GElGyAtbSWg==";
      };
    };
    "esbuild-linux-ppc64le-0.13.15" = {
      name = "esbuild-linux-ppc64le";
      packageName = "esbuild-linux-ppc64le";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-ppc64le/-/esbuild-linux-ppc64le-0.13.15.tgz";
        sha512 = "h6gYF+OsaqEuBjeesTBtUPw0bmiDu7eAeuc2OEH9S6mV9/jPhPdhOWzdeshb0BskRZxPhxPOjqZ+/OqLcxQwEQ==";
      };
    };
    "esbuild-netbsd-64-0.13.15" = {
      name = "esbuild-netbsd-64";
      packageName = "esbuild-netbsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-netbsd-64/-/esbuild-netbsd-64-0.13.15.tgz";
        sha512 = "3+yE9emwoevLMyvu+iR3rsa+Xwhie7ZEHMGDQ6dkqP/ndFzRHkobHUKTe+NCApSqG5ce2z4rFu+NX/UHnxlh3w==";
      };
    };
    "esbuild-openbsd-64-0.13.15" = {
      name = "esbuild-openbsd-64";
      packageName = "esbuild-openbsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-openbsd-64/-/esbuild-openbsd-64-0.13.15.tgz";
        sha512 = "wTfvtwYJYAFL1fSs8yHIdf5GEE4NkbtbXtjLWjM3Cw8mmQKqsg8kTiqJ9NJQe5NX/5Qlo7Xd9r1yKMMkHllp5g==";
      };
    };
    "esbuild-sunos-64-0.13.15" = {
      name = "esbuild-sunos-64";
      packageName = "esbuild-sunos-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-sunos-64/-/esbuild-sunos-64-0.13.15.tgz";
        sha512 = "lbivT9Bx3t1iWWrSnGyBP9ODriEvWDRiweAs69vI+miJoeKwHWOComSRukttbuzjZ8r1q0mQJ8Z7yUsDJ3hKdw==";
      };
    };
    "esbuild-windows-32-0.13.15" = {
      name = "esbuild-windows-32";
      packageName = "esbuild-windows-32";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-32/-/esbuild-windows-32-0.13.15.tgz";
        sha512 = "fDMEf2g3SsJ599MBr50cY5ve5lP1wyVwTe6aLJsM01KtxyKkB4UT+fc5MXQFn3RLrAIAZOG+tHC+yXObpSn7Nw==";
      };
    };
    "esbuild-windows-64-0.13.15" = {
      name = "esbuild-windows-64";
      packageName = "esbuild-windows-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.13.15.tgz";
        sha512 = "9aMsPRGDWCd3bGjUIKG/ZOJPKsiztlxl/Q3C1XDswO6eNX/Jtwu4M+jb6YDH9hRSUflQWX0XKAfWzgy5Wk54JQ==";
      };
    };
    "esbuild-windows-arm64-0.13.15" = {
      name = "esbuild-windows-arm64";
      packageName = "esbuild-windows-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-arm64/-/esbuild-windows-arm64-0.13.15.tgz";
        sha512 = "zzvyCVVpbwQQATaf3IG8mu1IwGEiDxKkYUdA4FpoCHi1KtPa13jeScYDjlW0Qh+ebWzpKfR2ZwvqAQkSWNcKjA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "eslint-7.32.0" = {
      name = "eslint";
      packageName = "eslint";
      version = "7.32.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint/-/eslint-7.32.0.tgz";
        sha512 = "VHZ8gX+EDfz+97jGcgyGCyRia/dPOd6Xh9yPv8Bl1+SoaIwD+a/vlrOmGRUyOYu7MwUhc7CxqeaDZU13S4+EpA==";
      };
    };
    "eslint-config-prettier-8.3.0" = {
      name = "eslint-config-prettier";
      packageName = "eslint-config-prettier";
      version = "8.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-config-prettier/-/eslint-config-prettier-8.3.0.tgz";
        sha512 = "BgZuLUSeKzvlL/VUjx/Yb787VQ26RU3gGjA3iiFvdsp/2bMfVIWUVP7tjxtjS0e+HP409cPlPvNkQloz8C91ew==";
      };
    };
    "eslint-plugin-svelte3-3.2.1" = {
      name = "eslint-plugin-svelte3";
      packageName = "eslint-plugin-svelte3";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-plugin-svelte3/-/eslint-plugin-svelte3-3.2.1.tgz";
        sha512 = "YoBR9mLoKCjGghJ/gvpnFZKaMEu/VRcuxpSRS8KuozuEo7CdBH7bmBHa6FmMm0i4kJnOyx+PVsaptz96K6H/4Q==";
      };
    };
    "eslint-scope-5.1.1" = {
      name = "eslint-scope";
      packageName = "eslint-scope";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-scope/-/eslint-scope-5.1.1.tgz";
        sha512 = "2NxwbF/hZ0KpepYN0cNbo+FN6XoK7GaHlQhgx/hIZl6Va0bF45RQOOwhLIy8lQDbuCiadSLCBnH2CFYquit5bw==";
      };
    };
    "eslint-utils-2.1.0" = {
      name = "eslint-utils";
      packageName = "eslint-utils";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-utils/-/eslint-utils-2.1.0.tgz";
        sha512 = "w94dQYoauyvlDc43XnGB8lU3Zt713vNChgt4EWwhXAP2XkBvndfxF0AgIqKOOasjPIPzj9JqgwkwbCYD0/V3Zg==";
      };
    };
    "eslint-visitor-keys-1.3.0" = {
      name = "eslint-visitor-keys";
      packageName = "eslint-visitor-keys";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-visitor-keys/-/eslint-visitor-keys-1.3.0.tgz";
        sha512 = "6J72N8UNa462wa/KFODt/PJ3IU60SDpC3QXC1Hjc1BXXpfL2C9R5+AU7jhe0F6GREqVMh4Juu+NY7xn+6dipUQ==";
      };
    };
    "eslint-visitor-keys-2.1.0" = {
      name = "eslint-visitor-keys";
      packageName = "eslint-visitor-keys";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-visitor-keys/-/eslint-visitor-keys-2.1.0.tgz";
        sha512 = "0rSmRBzXgDzIsD6mGdJgevzgezI534Cer5L/vyMX0kHzT/jiB43jRhd9YUlMGYLQy2zprNmoT8qasCGtY+QaKw==";
      };
    };
    "espree-7.3.1" = {
      name = "espree";
      packageName = "espree";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-7.3.1.tgz";
        sha512 = "v3JCNCE64umkFpmkFGqzVKsOT0tN1Zr+ueqLZfpV1Ob8e+CEgPWa+OxCoGH3tnhimMKIaBm4m/vaRpJ/krRz2g==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "esquery-1.4.0" = {
      name = "esquery";
      packageName = "esquery";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esquery/-/esquery-1.4.0.tgz";
        sha512 = "cCDispWt5vHHtwMY2YrAQ4ibFkAL8RbH5YGBnZBc90MolvvfkkQcJro/aZiAQUlQ3qgrYS6D6v8Gc5G5CQsc9w==";
      };
    };
    "esrecurse-4.3.0" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.3.0.tgz";
        sha512 = "KmfKL3b6G+RXvP8N1vr3Tq1kL/oCFgn2NYXEtqP8/L3pKapUA4G8cFVaoF3SU323CD4XypR/ffioHmkti6/Tag==";
      };
    };
    "estraverse-4.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.3.0.tgz";
        sha512 = "39nnKffWz8xN1BU/2c79n9nB9HDzo0niYUqx6xyqUnyoAnQyyWpOTdZEeiCch8BBu515t4wp9ZmgVfVhn9EBpw==";
      };
    };
    "estraverse-5.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.3.0.tgz";
        sha512 = "MMdARuVEQziNTeJD8DgMqmhwR11BRQ/cBP+pLtYdSTnf3MIO8fFeiINEbX36ZdNlfU/7A9f3gUw49B3oQsvwBA==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "file-entry-cache-6.0.1" = {
      name = "file-entry-cache";
      packageName = "file-entry-cache";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-entry-cache/-/file-entry-cache-6.0.1.tgz";
        sha512 = "7Gps/XWymbLk2QLYK4NzpMOrYjMhdIxXuIvy2QBsLE6ljuodKvdkWs/cpyJJ3CVIVpH0Oi1Hvg1ovbMzLdFBBg==";
      };
    };
    "flat-cache-3.0.4" = {
      name = "flat-cache";
      packageName = "flat-cache";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/flat-cache/-/flat-cache-3.0.4.tgz";
        sha512 = "dm9s5Pw7Jc0GvMYbshN6zchCA9RgQlzzEZX3vylR9IqFfS8XciblUXOKfW6SiuJ0e13eDYZoZV5wdrev7P3Nwg==";
      };
    };
    "flatted-3.2.4" = {
      name = "flatted";
      packageName = "flatted";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/flatted/-/flatted-3.2.4.tgz";
        sha512 = "8/sOawo8tJ4QOBX8YlQBMxL8+RLZfxMQOif9o0KUKTNTjMYElWPE0r/m5VNFxTRd0NSw8qSy8dajrwX4RYI1Hw==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "functional-red-black-tree-1.0.1" = {
      name = "functional-red-black-tree";
      packageName = "functional-red-black-tree";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/functional-red-black-tree/-/functional-red-black-tree-1.0.1.tgz";
        sha1 = "1b0ab3bd553b2a0d6399d29c0e3ea0b252078327";
      };
    };
    "glob-7.2.0" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.0.tgz";
        sha512 = "lmLf6gtyrPq8tTjSmrO94wBeQbFR3HbLHbuyD69wuyQkImp2hWqMGB47OX65FBkPffO641IP9jWa1z4ivqG26Q==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "globals-13.12.0" = {
      name = "globals";
      packageName = "globals";
      version = "13.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-13.12.0.tgz";
        sha512 = "uS8X6lSKN2JumVoXrbUz+uG4BYG+eiawqm3qFcT7ammfbUHeCBoJMlHcec/S3krSk73/AE/f0szYFmgAA3kYZg==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "ignore-4.0.6" = {
      name = "ignore";
      packageName = "ignore";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-4.0.6.tgz";
        sha512 = "cyFDKrqc/YdcWFniJhzI42+AzS+gNwmUzOSFcRCQYwySuBBBy/KjuxWLZ/FHEH6Moq1NizMOBWyTcv8O4OZIMg==";
      };
    };
    "import-fresh-3.3.0" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-3.3.0.tgz";
        sha512 = "veYYhQa+D1QBKznvhUHxb8faxlrwUnxseDAbAp457E0wLNio2bOSKnjYDhMj+YiAq61xrMGhQk9iXVk5FzgQMw==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-core-module-2.8.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.8.0.tgz";
        sha512 = "vd15qHsaqrRL7dtH6QNuy0ndJmRDrS9HAM1CAiSifNUFv4x1a0CCVsj18hJ1mShxIG6T2i1sO78MkP56r0nYRw==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "js-yaml-3.14.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz";
        sha512 = "okMH7OXXJ7YrN9Ok3/SXrnu4iX9yOk+25nqX4imS2npuvTYDmo/QEZoqwZkYaIDk3jVvBOTOIEgEhaLOynBS9g==";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-schema-traverse-1.0.0" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
        sha512 = "NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
      };
    };
    "json-stable-stringify-without-jsonify-1.0.1" = {
      name = "json-stable-stringify-without-jsonify";
      packageName = "json-stable-stringify-without-jsonify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz";
        sha1 = "9db7b59496ad3f3cfef30a75142d2d930ad72651";
      };
    };
    "kleur-4.1.4" = {
      name = "kleur";
      packageName = "kleur";
      version = "4.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/kleur/-/kleur-4.1.4.tgz";
        sha512 = "8QADVssbrFjivHWQU7KkMgptGTl6WAcSdlbBPY4uNF+mWr6DGcKrvY2w4FQJoXch7+fKMjj0dRrL75vk3k23OA==";
      };
    };
    "levn-0.4.1" = {
      name = "levn";
      packageName = "levn";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.4.1.tgz";
        sha512 = "+bT2uH4E5LGE7h/n3evcS/sQlJXCpIp6ym8OWJ5eV6+67Dsql/LaaT7qJBAt2rzfoa/5QBGBhxDix1dMt2kQKQ==";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "lodash.truncate-4.4.2" = {
      name = "lodash.truncate";
      packageName = "lodash.truncate";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.truncate/-/lodash.truncate-4.4.2.tgz";
        sha1 = "5a350da0b1113b837ecfffd5812cbe58d6eae193";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "magic-string-0.25.7" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.25.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.25.7.tgz";
        sha512 = "4CrMT5DOHTDk4HYDlzmwu4FVCcIYI8gauveasrdCu2IKIFOJ3f0v/8MDGJCDL9oD2ppz/Av1b0Nj345H9M+XIA==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "mri-1.2.0" = {
      name = "mri";
      packageName = "mri";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
        sha512 = "tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "nanoid-3.1.30" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.1.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.1.30.tgz";
        sha512 = "zJpuPDwOv8D2zq2WRoMe1HsfZthVewpel9CAvTfc/2mBD1uUT/agc5f7GHGWXlYkFvi1mVxe4IjvP2HNrop7nQ==";
      };
    };
    "natural-compare-1.4.0" = {
      name = "natural-compare";
      packageName = "natural-compare";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/natural-compare/-/natural-compare-1.4.0.tgz";
        sha1 = "4abebfeed7541f2c27acfb29bdbbd15c8d5ba4f7";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "optionator-0.9.1" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.9.1.tgz";
        sha512 = "74RlY5FCnhq4jRxVUPKDaRwrVNXMqsGsiW6AJw4XK8hmtm10wC0ypZBLw5IIp85NZMr91+qd1RvvENwg7jjRFw==";
      };
    };
    "parent-module-1.0.1" = {
      name = "parent-module";
      packageName = "parent-module";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parent-module/-/parent-module-1.0.1.tgz";
        sha512 = "GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "picomatch-2.3.0" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.0.tgz";
        sha512 = "lY1Q/PiJGC2zOv/z391WOTD+Z02bCgsFfvxoXXf6h7kv9o+WmsmzYqrAwY63sNgOxE4xEdq0WyUnXfKeBrSvYw==";
      };
    };
    "postcss-8.4.1" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.1.tgz";
        sha512 = "WqLs/TTzXdG+/A4ZOOK9WDZiikrRaiA+eoEb/jz2DT9KUhMNHgP7yKPO8vwi62ZCsb703Gwb7BMZwDzI54Y2Ag==";
      };
    };
    "prelude-ls-1.2.1" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.2.1.tgz";
        sha512 = "vkcDPrRZo1QZLbn5RLGPpg/WmIQ65qoWWhcGKf/b5eplkkarX0m9z8ppCat4mlOqUsWpyNuYgO3VRyrYHSzX5g==";
      };
    };
    "prettier-2.5.0" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.5.0.tgz";
        sha512 = "FM/zAKgWTxj40rH03VxzIPdXmj39SwSjwG0heUcNFwI+EMZJnY93yAiKXM3dObIKAM5TA88werc8T/EwhB45eg==";
      };
    };
    "prettier-plugin-svelte-2.5.0" = {
      name = "prettier-plugin-svelte";
      packageName = "prettier-plugin-svelte";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-svelte/-/prettier-plugin-svelte-2.5.0.tgz";
        sha512 = "+iHY2uGChOngrgKielJUnqo74gIL/EO5oeWm8MftFWjEi213lq9QYTOwm1pv4lI1nA61tdgf80CF2i5zMcu1kw==";
      };
    };
    "progress-2.0.3" = {
      name = "progress";
      packageName = "progress";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-2.0.3.tgz";
        sha512 = "7PiHtLll5LdnKIMw100I+8xJXR5gW2QwWYkT6iJva0bXitZKa/XMrSbdmg3r2Xnaidz9Qumd0VPaMrZlF9V9sA==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "regexpp-3.2.0" = {
      name = "regexpp";
      packageName = "regexpp";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexpp/-/regexpp-3.2.0.tgz";
        sha512 = "pq2bWo9mVD43nbts2wGv17XLiNLya+GklZ8kaDLV2Z08gDCsGpnKn9BFMepvWuHCbyVvY7J5o5+BVvoQbmlJLg==";
      };
    };
    "require-from-string-2.0.2" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
        sha512 = "Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
      };
    };
    "require-relative-0.8.7" = {
      name = "require-relative";
      packageName = "require-relative";
      version = "0.8.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-relative/-/require-relative-0.8.7.tgz";
        sha1 = "7999539fc9e047a37928fa196f8e1563dabd36de";
      };
    };
    "resolve-1.20.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.20.0.tgz";
        sha512 = "wENBPt4ySzg4ybFQW2TT1zMQucPK95HSh/nq2CFTZVOGut2+pQvSsgtda4d26YrYcr067wjbmzOG8byDPBX63A==";
      };
    };
    "resolve-from-4.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz";
        sha512 = "pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "rollup-2.60.1" = {
      name = "rollup";
      packageName = "rollup";
      version = "2.60.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-2.60.1.tgz";
        sha512 = "akwfnpjY0rXEDSn1UTVfKXJhPsEBu+imi1gqBA1ZkHGydUnkV/fWCC90P7rDaLEW8KTwBcS1G3N4893Ndz+jwg==";
      };
    };
    "sade-1.7.4" = {
      name = "sade";
      packageName = "sade";
      version = "1.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sade/-/sade-1.7.4.tgz";
        sha512 = "y5yauMD93rX840MwUJr7C1ysLFBgMspsdTo4UVrDg3fXDvtwOyIqykhVAAm6fk/3au77773itJStObgK+LKaiA==";
      };
    };
    "semver-7.3.5" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.5.tgz";
        sha512 = "PoeGJYh8HK4BTO/a9Tf6ZG3veo/A7ZVsYrSA6J8ny9nb3B1VrpkuN+z9OE5wfE5p6H4LchYZsegiQgbJD94ZFQ==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "slice-ansi-4.0.0" = {
      name = "slice-ansi";
      packageName = "slice-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-4.0.0.tgz";
        sha512 = "qMCMfhY040cVHT43K9BFygqYbUPFZKHOg7K73mtTWJRb8pyP3fzf4Ixd5SzdEJQ6MRUg/WBnOLxghZtKKurENQ==";
      };
    };
    "source-map-js-1.0.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.1.tgz";
        sha512 = "4+TN2b3tqOCd/kaGRJ/sTYA0tR0mdXx26ipdolxcwtJVqEnqNYvlCAt1q3ypy4QMlYus+Zh34RNtYLoq2oQ4IA==";
      };
    };
    "sourcemap-codec-1.4.8" = {
      name = "sourcemap-codec";
      packageName = "sourcemap-codec";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sourcemap-codec/-/sourcemap-codec-1.4.8.tgz";
        sha512 = "9NykojV5Uih4lgo5So5dtw+f0JgJX30KCNI8gwhz2J9A15wD0Ml6tjHKwf6fTSa6fAdVBdZeNOs9eJ71qCk8vA==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-json-comments-3.1.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
        sha512 = "6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "svelte-3.44.2" = {
      name = "svelte";
      packageName = "svelte";
      version = "3.44.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-3.44.2.tgz";
        sha512 = "jrZhZtmH3ZMweXg1Q15onb8QlWD+a5T5Oca4C1jYvSURp2oD35h4A5TV6t6MEa93K4LlX6BkafZPdQoFjw/ylA==";
      };
    };
    "svelte-hmr-0.14.8" = {
      name = "svelte-hmr";
      packageName = "svelte-hmr";
      version = "0.14.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte-hmr/-/svelte-hmr-0.14.8.tgz";
        sha512 = "BK1uLmiKHHSVh517oeFd8BO6aRMgYz+MfhbX4p2aXeNHVqZIEZpvF81bbtSDKJGWaBVDMPoG2Q4whkkyNK9I2g==";
      };
    };
    "table-6.7.3" = {
      name = "table";
      packageName = "table";
      version = "6.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/table/-/table-6.7.3.tgz";
        sha512 = "5DkIxeA7XERBqMwJq0aHZOdMadBx4e6eDoFRuyT5VR82J0Ycg2DwM6GfA/EQAhJ+toRTaS1lIdSQCqgrmhPnlw==";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha1 = "7f5ee823ae805207c00af2df4a84ec3fcfa570b4";
      };
    };
    "type-check-0.4.0" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.4.0.tgz";
        sha512 = "XleUoc9uwGXqjWwXaUTZAmzMcFZ5858QA2vvx1Ur5xIcixXIP+8LnFDgRplU30us6teqdlskFfu+ae4K79Ooew==";
      };
    };
    "type-fest-0.20.2" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.20.2.tgz";
        sha512 = "Ne+eE4r0/iWnpAxD852z3A+N0Bt5RN//NjJwRd2VFHEmrywxf5vsZlh4R6lixl6B+wz/8d+maTSAkN1FIkI3LQ==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "v8-compile-cache-2.3.0" = {
      name = "v8-compile-cache";
      packageName = "v8-compile-cache";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8-compile-cache/-/v8-compile-cache-2.3.0.tgz";
        sha512 = "l8lCEmLcLYZh4nbunNZvQCJc5pv7+RCwa8q/LdUx8u7lsWvPDKmpodJAJNwkAhJC//dFY48KuIEmjtd4RViDrA==";
      };
    };
    "vite-2.6.14" = {
      name = "vite";
      packageName = "vite";
      version = "2.6.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/vite/-/vite-2.6.14.tgz";
        sha512 = "2HA9xGyi+EhY2MXo0+A2dRsqsAG3eFNEVIo12olkWhOmc8LfiM+eMdrXf+Ruje9gdXgvSqjLI9freec1RUM5EA==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "word-wrap-1.2.3" = {
      name = "word-wrap";
      packageName = "word-wrap";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/word-wrap/-/word-wrap-1.2.3.tgz";
        sha512 = "Hz/mrNwitNRh/HUAtM/VT/5VH+ygD6DV7mYKZAtHOrbs8U7lvPS6xf7EJKMF0uW1KJCl0H701g3ZGus+muE5vQ==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
  args = {
    name = "sveltekit";
    packageName = "sveltekit";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."@babel/code-frame-7.12.11"
      sources."@babel/helper-validator-identifier-7.15.7"
      (sources."@babel/highlight-7.16.0" // {
        dependencies = [
          sources."chalk-2.4.2"
          sources."escape-string-regexp-1.0.5"
        ];
      })
      sources."@eslint/eslintrc-0.4.3"
      sources."@fontsource/fira-mono-4.5.0"
      sources."@humanwhocodes/config-array-0.5.0"
      sources."@humanwhocodes/object-schema-1.2.1"
      sources."@iarna/toml-2.2.5"
      sources."@lukeed/csprng-1.0.1"
      sources."@lukeed/uuid-2.0.0"
      sources."@rollup/pluginutils-4.1.1"
      sources."@sveltejs/adapter-auto-1.0.0-next.3"
      sources."@sveltejs/adapter-cloudflare-1.0.0-next.2"
      sources."@sveltejs/adapter-netlify-1.0.0-next.35"
      sources."@sveltejs/adapter-static-1.0.0-next.21"
      sources."@sveltejs/adapter-vercel-1.0.0-next.31"
      sources."@sveltejs/kit-1.0.0-next.201"
      sources."@sveltejs/vite-plugin-svelte-1.0.0-next.30"
      sources."acorn-7.4.1"
      sources."acorn-jsx-5.3.2"
      sources."ajv-6.12.6"
      sources."ansi-colors-4.1.1"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-3.2.1"
      sources."argparse-1.0.10"
      sources."astral-regex-2.0.0"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."callsites-3.1.0"
      (sources."chalk-4.1.2" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
        ];
      })
      sources."cheap-watch-1.0.4"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."cookie-0.4.1"
      sources."cross-spawn-7.0.3"
      sources."debug-4.3.2"
      sources."deep-is-0.1.4"
      sources."doctrine-3.0.0"
      sources."emoji-regex-8.0.0"
      sources."enquirer-2.3.6"
      sources."esbuild-0.13.15"
      sources."esbuild-android-arm64-0.13.15"
      sources."esbuild-darwin-64-0.13.15"
      sources."esbuild-darwin-arm64-0.13.15"
      sources."esbuild-freebsd-64-0.13.15"
      sources."esbuild-freebsd-arm64-0.13.15"
      sources."esbuild-linux-32-0.13.15"
      sources."esbuild-linux-64-0.13.15"
      sources."esbuild-linux-arm-0.13.15"
      sources."esbuild-linux-arm64-0.13.15"
      sources."esbuild-linux-mips64le-0.13.15"
      sources."esbuild-linux-ppc64le-0.13.15"
      sources."esbuild-netbsd-64-0.13.15"
      sources."esbuild-openbsd-64-0.13.15"
      sources."esbuild-sunos-64-0.13.15"
      sources."esbuild-windows-32-0.13.15"
      sources."esbuild-windows-64-0.13.15"
      sources."esbuild-windows-arm64-0.13.15"
      sources."escape-string-regexp-4.0.0"
      sources."eslint-7.32.0"
      sources."eslint-config-prettier-8.3.0"
      sources."eslint-plugin-svelte3-3.2.1"
      sources."eslint-scope-5.1.1"
      (sources."eslint-utils-2.1.0" // {
        dependencies = [
          sources."eslint-visitor-keys-1.3.0"
        ];
      })
      sources."eslint-visitor-keys-2.1.0"
      (sources."espree-7.3.1" // {
        dependencies = [
          sources."eslint-visitor-keys-1.3.0"
        ];
      })
      sources."esprima-4.0.1"
      (sources."esquery-1.4.0" // {
        dependencies = [
          sources."estraverse-5.3.0"
        ];
      })
      (sources."esrecurse-4.3.0" // {
        dependencies = [
          sources."estraverse-5.3.0"
        ];
      })
      sources."estraverse-4.3.0"
      sources."estree-walker-2.0.2"
      sources."esutils-2.0.3"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fast-levenshtein-2.0.6"
      sources."file-entry-cache-6.0.1"
      sources."flat-cache-3.0.4"
      sources."flatted-3.2.4"
      sources."fs.realpath-1.0.0"
      sources."fsevents-2.3.2"
      sources."function-bind-1.1.1"
      sources."functional-red-black-tree-1.0.1"
      sources."glob-7.2.0"
      sources."glob-parent-5.1.2"
      sources."globals-13.12.0"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."ignore-4.0.6"
      sources."import-fresh-3.3.0"
      sources."imurmurhash-0.1.4"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-core-module-2.8.0"
      sources."is-extglob-2.1.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-glob-4.0.3"
      sources."isexe-2.0.0"
      sources."js-tokens-4.0.0"
      sources."js-yaml-3.14.1"
      sources."json-schema-traverse-0.4.1"
      sources."json-stable-stringify-without-jsonify-1.0.1"
      sources."kleur-4.1.4"
      sources."levn-0.4.1"
      sources."lodash.merge-4.6.2"
      sources."lodash.truncate-4.4.2"
      sources."lru-cache-6.0.0"
      sources."magic-string-0.25.7"
      sources."minimatch-3.0.4"
      sources."mri-1.2.0"
      sources."ms-2.1.2"
      sources."nanoid-3.1.30"
      sources."natural-compare-1.4.0"
      sources."once-1.4.0"
      sources."optionator-0.9.1"
      sources."parent-module-1.0.1"
      sources."path-is-absolute-1.0.1"
      sources."path-key-3.1.1"
      sources."path-parse-1.0.7"
      sources."picocolors-1.0.0"
      sources."picomatch-2.3.0"
      sources."postcss-8.4.1"
      sources."prelude-ls-1.2.1"
      sources."prettier-2.5.0"
      sources."prettier-plugin-svelte-2.5.0"
      sources."progress-2.0.3"
      sources."punycode-2.1.1"
      sources."regexpp-3.2.0"
      sources."require-from-string-2.0.2"
      sources."require-relative-0.8.7"
      sources."resolve-1.20.0"
      sources."resolve-from-4.0.0"
      sources."rimraf-3.0.2"
      sources."rollup-2.60.1"
      sources."sade-1.7.4"
      sources."semver-7.3.5"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      (sources."slice-ansi-4.0.0" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
        ];
      })
      sources."source-map-js-1.0.1"
      sources."sourcemap-codec-1.4.8"
      sources."sprintf-js-1.0.3"
      sources."string-width-4.2.3"
      sources."strip-ansi-6.0.1"
      sources."strip-json-comments-3.1.1"
      sources."supports-color-5.5.0"
      sources."svelte-3.44.2"
      sources."svelte-hmr-0.14.8"
      (sources."table-6.7.3" // {
        dependencies = [
          sources."ajv-8.8.2"
          sources."json-schema-traverse-1.0.0"
        ];
      })
      sources."text-table-0.2.0"
      sources."type-check-0.4.0"
      sources."type-fest-0.20.2"
      sources."uri-js-4.4.1"
      sources."v8-compile-cache-2.3.0"
      sources."vite-2.6.14"
      sources."which-2.0.2"
      sources."word-wrap-1.2.3"
      sources."wrappy-1.0.2"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = false;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
